(function (root, factory) {
  if (typeof module === "object" && module.exports) {
    module.exports = factory();
    return;
  }

  var api = factory();
  root.radicalRedItemConstants = api;
  root.rrItems = api.items;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  return {
  "items": [
    "None",
    "Master Ball",
    "Ultra Ball",
    "Great Ball",
    "Poke Ball",
    "Safari Ball",
    "Net Ball",
    "Dive Ball",
    "Nest Ball",
    "Repeat Ball",
    "Timer Ball",
    "Luxury Ball",
    "Premier Ball",
    "Potion",
    "Antidote",
    "Burn Heal",
    "Ice Heal",
    "Awakening",
    "Paralyze Heal",
    "Full Restore",
    "Max Potion",
    "Hyper Potion",
    "Super Potion",
    "Full Heal",
    "Revive",
    "Max Revive",
    "Fresh Water",
    "Soda Pop",
    "Lemonade",
    "Moomoo Milk",
    "EnergyPowder",
    "Energy Root",
    "Heal Powder",
    "Revival Herb",
    "Ether",
    "Max Ether",
    "Elixir",
    "Max Elixir",
    "Lava Cookie",
    "Blue Flute",
    "Yellow Flute",
    "Red Flute",
    "Black Flute",
    "White Flute",
    "Berry Juice",
    "Sacred Ash",
    "Shoal Salt",
    "Shoal Shell",
    "Red Shard",
    "Blue Shard",
    "Yellow Shard",
    "Green Shard",
    "Rage Candy Bar",
    "Old Gateau",
    "Casteliacone",
    "Dream Patch",
    "Shalour Sable",
    "Health Wing",
    "Muscle Wing",
    "Resist Wing",
    "Genius Wing",
    "Clever Wing",
    "Swift Wing",
    "HP Up",
    "Protein",
    "Iron",
    "Carbos",
    "Calcium",
    "Rare Candy",
    "PP Up",
    "Zinc",
    "PP Max",
    "Ability Pill",
    "Guard Spec.",
    "Dire Hit",
    "X Attack",
    "X Defend",
    "X Speed",
    "X Accuracy",
    "X Sp. Atk",
    "Poke Doll",
    "Fluffy Tail",
    "Big Malasada",
    "Super Repel",
    "Max Repel",
    "Escape Rope",
    "Repel",
    "Link Cable",
    "Protector",
    "Electirizer",
    "Magmarizer",
    "Dubious Disc",
    "Reaper Cloth",
    "Sun Stone",
    "Moon Stone",
    "Fire Stone",
    "ThunderStone",
    "Water Stone",
    "Leaf Stone",
    "Shiny Stone",
    "Dusk Stone",
    "Dawn Stone",
    "Ice Stone",
    "TinyMushroom",
    "Big Mushroom",
    "BalmMushroom",
    "Pearl",
    "Big Pearl",
    "Stardust",
    "Star Piece",
    "Nugget",
    "Heart Scale",
    "Rare Bone",
    "Pearl String",
    "Comet Shard",
    "Big Nugget",
    "Honey",
    "Pretty Wing",
    "Oval Stone",
    "Razor Claw",
    "Razor Fang",
    "Orange Mail",
    "Harbor Mail",
    "Glitter Mail",
    "Mech Mail",
    "Wood Mail",
    "Wave Mail",
    "Bead Mail",
    "Shadow Mail",
    "Tropic Mail",
    "Dream Mail",
    "Fab Mail",
    "Retro Mail",
    "Cheri Berry",
    "Chesto Berry",
    "Pecha Berry",
    "Rawst Berry",
    "Aspear Berry",
    "Leppa Berry",
    "Oran Berry",
    "Persim Berry",
    "Lum Berry",
    "Sitrus Berry",
    "Figy Berry",
    "Wiki Berry",
    "Mago Berry",
    "Aguav Berry",
    "Iapapa Berry",
    "Razz Berry",
    "Bluk Berry",
    "Nanab Berry",
    "Wepear Berry",
    "Pinap Berry",
    "Pomeg Berry",
    "Kelpsy Berry",
    "Qualot Berry",
    "Hondew Berry",
    "Grepa Berry",
    "Tamato Berry",
    "Cornn Berry",
    "Magost Berry",
    "Rabuta Berry",
    "Nomel Berry",
    "Spelon Berry",
    "Pamtre Berry",
    "Watmel Berry",
    "Durin Berry",
    "Belue Berry",
    "Liechi Berry",
    "Ganlon Berry",
    "Salac Berry",
    "Petaya Berry",
    "Apicot Berry",
    "Lansat Berry",
    "Starf Berry",
    "Enigma Berry",
    "Prism Scale",
    "Sachet",
    "Whip Dream",
    "BrightPowder",
    "White Herb",
    "Macho Brace",
    "Exp. Share",
    "Quick Claw",
    "Soothe Bell",
    "Mental Herb",
    "Choice Band",
    "King's Rock",
    "SilverPowder",
    "Amulet Coin",
    "Cleanse Tag",
    "Soul Dew",
    "Deep Sea Tooth",
    "Deep Sea Scale",
    "Smoke Ball",
    "Everstone",
    "Focus Band",
    "Lucky Egg",
    "Scope Lens",
    "Metal Coat",
    "Leftovers",
    "Dragon Scale",
    "Light Ball",
    "Soft Sand",
    "Hard Stone",
    "Miracle Seed",
    "Black Glasses",
    "Black Belt",
    "Magnet",
    "Mystic Water",
    "Sharp Beak",
    "Poison Barb",
    "Never-Melt Ice",
    "Spell Tag",
    "Twisted Spoon",
    "Charcoal",
    "Dragon Fang",
    "Silk Scarf",
    "Upgrade",
    "Shell Bell",
    "Sea Incense",
    "Lax Incense",
    "Lucky Punch",
    "Metal Powder",
    "Thick Club",
    "Leek Stick",
    "Strawberry Sweet",
    "Berry Sweet",
    "Love Sweet",
    "Clover Sweet",
    "Flower Sweet",
    "Ribbon Sweet",
    "Star Sweet",
    "Sweet Apple",
    "Tart Apple",
    "Cracked Pot",
    "Chipped Pot",
    "Galar Cuff",
    "Galar Crown",
    "Cherish Ball",
    "Dusk Ball",
    "Heal Ball",
    "Quick Ball",
    "Fast Ball",
    "Level Ball",
    "Lure Ball",
    "Heavy Ball",
    "Love Ball",
    "Friend Ball",
    "Moon Ball",
    "Sport Ball",
    "Beast Ball",
    "Dream Ball",
    "Park Ball",
    "Red Scarf",
    "Blue Scarf",
    "Pink Scarf",
    "Green Scarf",
    "Yellow Scarf",
    "Mach Bike",
    "Coin Case",
    "Itemfinder",
    "Old Rod",
    "Good Rod",
    "Super Rod",
    "S.S. Ticket",
    "Contest Pass",
    "Z-Power Ring",
    "Wailmer Pail",
    "Devon Goods",
    "Soot Sack",
    "Basement Key",
    "Acro Bike",
    "PokeBlock Case",
    "Letter",
    "Eon Ticket",
    "Red Orb",
    "Blue Orb",
    "Scanner",
    "Go-Goggles",
    "Meteorite",
    "RM. 1 Key",
    "RM. 2 Key",
    "RM. 4 Key",
    "RM. 6 Key",
    "Storage Key",
    "Root Fossil",
    "Claw Fossil",
    "Devon Scope",
    "TM01",
    "TM02",
    "TM03",
    "TM04",
    "TM05",
    "TM06",
    "TM07",
    "TM08",
    "TM09",
    "TM10",
    "TM11",
    "TM12",
    "TM13",
    "TM14",
    "TM15",
    "TM16",
    "TM17",
    "TM18",
    "TM19",
    "TM20",
    "TM21",
    "TM22",
    "TM23",
    "TM24",
    "TM25",
    "TM26",
    "TM27",
    "TM28",
    "TM29",
    "TM30",
    "TM31",
    "TM32",
    "TM33",
    "TM34",
    "TM35",
    "TM36",
    "TM37",
    "TM38",
    "TM39",
    "TM40",
    "TM41",
    "TM42",
    "TM43",
    "TM44",
    "TM45",
    "TM46",
    "TM47",
    "TM48",
    "TM49",
    "TM50",
    "HM01",
    "HM02",
    "HM03",
    "HM04",
    "HM05",
    "HM06",
    "HM07",
    "HM08",
    "Dynamax Band",
    "Gold Teeth",
    "Oak's Parcel",
    "Poke Flute",
    "Secret Key",
    "Bike Voucher",
    "Mega Ring",
    "Old Amber",
    "Card Key",
    "Lift Key",
    "Helix Fossil",
    "Dome Fossil",
    "Silph Scope",
    "Bicycle",
    "Town Map",
    "Stat Scanner",
    "Poke Rider",
    "TM Case",
    "Berry Pouch",
    "Teachy TV",
    "Tri-Pass",
    "Rainbow Pass",
    "Tea",
    "Mystic Ticket",
    "Aurora Ticket",
    "Locater",
    "Ruby",
    "Sapphire",
    "-DONT USE-",
    "TM51",
    "TM52",
    "TM53",
    "TM54",
    "TM55",
    "TM56",
    "TM57",
    "TM58",
    "TM59",
    "TM60",
    "TM61",
    "TM62",
    "TM63",
    "TM64",
    "TM65",
    "TM66",
    "TM67",
    "TM68",
    "TM69",
    "TM70",
    "TM71",
    "TM72",
    "TM73",
    "TM74",
    "TM75",
    "TM76",
    "TM77",
    "TM78",
    "TM79",
    "TM80",
    "TM81",
    "TM82",
    "TM83",
    "TM84",
    "TM85",
    "TM86",
    "TM87",
    "TM88",
    "TM89",
    "TM90",
    "TM91",
    "TM92",
    "TM93",
    "TM94",
    "TM95",
    "TM96",
    "TM97",
    "TM98",
    "TM99",
    "TM100",
    "TM101",
    "TM102",
    "TM103",
    "TM104",
    "TM105",
    "TM106",
    "TM107",
    "TM108",
    "TM109",
    "TM110",
    "TM111",
    "TM112",
    "TM113",
    "TM114",
    "TM115",
    "TM116",
    "TM117",
    "TM118",
    "TM119",
    "TM120",
    "Occa Berry",
    "Passho Berry",
    "Wacan Berry",
    "Rindo Berry",
    "Yache Berry",
    "Chople Berry",
    "Kebia Berry",
    "Shuca Berry",
    "Coba Berry",
    "Payapa Berry",
    "Tanga Berry",
    "Charti Berry",
    "Kasib Berry",
    "Haban Berry",
    "Colbur Berry",
    "Babiri Berry",
    "Chilan Berry",
    "Micle Berry",
    "Custap Berry",
    "Jacoba Berry",
    "Rowap Berry",
    "Roseli Berry",
    "Kee Berry",
    "Marang Berry",
    "Oval Charm",
    "Shiny Charm",
    "Rainbow Wing",
    "Silver Wing",
    "Magma Stone",
    "Light Stone",
    "Dark Stone",
    "Sun Flute",
    "Moon Flute",
    "Gracidea",
    "DNA Splicers",
    "Reveal Glass",
    "Prison Bottle",
    "N-Solarizer",
    "Necrozmizer",
    "Rusty Sword",
    "Rusty Shield",
    "Adamant Orb",
    "Lustrous Orb",
    "Griseous Orb",
    "Fist Plate",
    "Sky Plate",
    "Toxic Plate",
    "Earth Plate",
    "Stone Plate",
    "Insect Plate",
    "Spooky Plate",
    "Iron Plate",
    "Flame Plate",
    "Splash Plate",
    "Meadow Plate",
    "Zap Plate",
    "Mind Plate",
    "Icicle Plate",
    "Draco Plate",
    "Dread Plate",
    "Pixie Plate",
    "Fight Memory",
    "Flying Memory",
    "Poison Memory",
    "Ground Memory",
    "Rock Memory",
    "Bug Memory",
    "Ghost Memory",
    "Steel Memory",
    "Fire Memory",
    "Water Memory",
    "Grass Memory",
    "Electric Memory",
    "Psychic Memory",
    "Ice Memory",
    "Dragon Memory",
    "Dark Memory",
    "Fairy Memory",
    "Burn Drive",
    "Douse Drive",
    "Shock Drive",
    "Chill Drive",
    "Red Nectar",
    "Yellow Nectar",
    "Pink Nectar",
    "Purple Nectar",
    "Necrozium Z",
    "Venusaurite",
    "Charzardite X",
    "Charzardite Y",
    "Blastoisnite",
    "Beedrillite",
    "Pidgeotite",
    "Alakazite",
    "Slowbronite",
    "Gengarite",
    "Kangaskanite",
    "Pinsirite",
    "Gyaradosite",
    "Aerodactlite",
    "Mewtwonite X",
    "Mewtwonite Y",
    "Ampharosite",
    "Steelixite",
    "Scizorite",
    "Heracronite",
    "Houndoomnite",
    "Tyranitarite",
    "Sceptilite",
    "Blazikenite",
    "Swampertite",
    "Gardevoirite",
    "Sablenite",
    "Mawilite",
    "Aggronite",
    "Medichamite",
    "Manectite",
    "Sharpedonite",
    "Cameruptite",
    "Altarianite",
    "Banettite",
    "Absolite",
    "Glalitite",
    "Salamencite",
    "Metagrossite",
    "Latiasite",
    "Latiosite",
    "Lopunnite",
    "Garchompite",
    "Lucarionite",
    "Abomasite",
    "Galladite",
    "Audinite",
    "Diancite",
    "Normalium Z",
    "Fightinium Z",
    "Flyinium Z",
    "Poisonium Z",
    "Groundium Z",
    "Rockium Z",
    "Buginium Z",
    "Ghostium Z",
    "Steelium Z",
    "Firium Z",
    "Waterium Z",
    "Grassium Z",
    "Electrium Z",
    "Psychium Z",
    "Icium Z",
    "Dragonium Z",
    "Darkinium Z",
    "Fairium Z",
    "Alorichium Z",
    "Decidium Z",
    "Eevium Z",
    "Incinium Z",
    "Kommonium Z",
    "Lunalium Z",
    "Lycanium Z",
    "Marshadium Z",
    "Mewnium Z",
    "Mimikium Z",
    "Pikanium Z",
    "Pikshunium Z",
    "Primarium Z",
    "Snorlium Z",
    "Solganium Z",
    "Tapunium Z",
    "Booster Energy",
    "Loaded Dice",
    "Clear Amulet",
    "Ability Shield",
    "Mirror Herb",
    "Upgrade",
    "Electirizer",
    "Cornerstone Mask",
    "Hearthflame Mask",
    "Wellspring Mask",
    "Teal Mask",
    "Burnt Seed",
    "Magmarizer",
    "Relic Crown",
    "Skull Fossil",
    "Armor Fossil",
    "Cover Fossil",
    "Plume Fossil",
    "Jaw Fossil",
    "Sail Fossil",
    "Bird Fossil",
    "Fish Fossil",
    "Drake Fossil",
    "Dino Fossil",
    "Odd Keystone",
    "Bottle Cap",
    "Gold Bottle Cap",
    "Wishing Piece",
    "Power Bracer",
    "Power Belt",
    "Power Lens",
    "Power Band",
    "Power Anklet",
    "Power Weight",
    "Luck Incense",
    "Full Incense",
    "Odd Incense",
    "Pure Incense",
    "Rock Incense",
    "Rose Incense",
    "Wave Incense",
    "Normal Gem",
    "Fighting Gem",
    "Flying Gem",
    "Poison Gem",
    "Ground Gem",
    "Rock Gem",
    "Bug Gem",
    "Ghost Gem",
    "Steel Gem",
    "Fire Gem",
    "Water Gem",
    "Grass Gem",
    "Electric Gem",
    "Psychic Gem",
    "Ice Gem",
    "Dragon Gem",
    "Dark Gem",
    "Fairy Gem",
    "Wide Lens",
    "Muscle Band",
    "Wise Glasses",
    "Expert Belt",
    "Light Clay",
    "Life Orb",
    "Power Herb",
    "Toxic Orb",
    "Flame Orb",
    "Quick Powder",
    "Focus Sash",
    "Zoom Lens",
    "Metronome",
    "Iron Ball",
    "Lagging Tail",
    "Destiny Knot",
    "Black Sludge",
    "Icy Rock",
    "Smooth Rock",
    "Heat Rock",
    "Damp Rock",
    "Grip Claw",
    "Choice Scarf",
    "Choice Specs",
    "Sticky Barb",
    "Shed Shell",
    "Big Root",
    "Eviolite",
    "Float Stone",
    "Rocky Helmet",
    "Air Balloon",
    "Red Card",
    "Ring Target",
    "Binding Band",
    "Absorb Bulb",
    "Cell Battery",
    "Eject Button",
    "Weakness Policy",
    "Assault Vest",
    "Luminous Moss",
    "Snowball",
    "Safety Goggles",
    "Adrenaline Orb",
    "Terrain Extender",
    "Protective Pads",
    "Electric Seed",
    "Grassy Seed",
    "Misty Seed",
    "Psychic Seed",
    "Eject Pack",
    "Room Service",
    "Blunder Policy",
    "Heavy-Duty Boots",
    "Utility Umbrella",
    "Throat Spray",
    "Machampite",
    "Laprasite",
    "Butterfrite",
    "Garbodorite",
    "Snorlaxite",
    "Kinglerite",
    "Toxtricitite",
    "Coalossite",
    "Duraludite",
    "Drednawite",
    "Copperajite",
    "Applite",
    "Orbeetlite",
    "Grimmsnite",
    "Medicine",
    "Centiskite",
    "Sandacondite",
    "Alcremite",
    "Eternamax Orb",
    "Punching Glove",
    "Covert Cloak",
    "Free Space22"
  ],
  "itemDescriptions": [
    "",
    "The best Ball with the ultimate performance. It will catch any wild Pokemon without fail.",
    "A very high-grade Ball that offers a higher Pokemon catch rate than a Great Ball.",
    "A good, quality Ball that offers a higher Pokemon catch rate than a standard Poke Ball.",
    "A Ball thrown to catch a wild Pokemon. It is designed in a capsule style.",
    "A special Ball that is used only in the Safari Zone. It is finished in a camouflage pattern.",
    "A somewhat different Ball that works especially well on Water- and Bug-type Pokemon.",
    "A somewhat different Ball that works especially well on Pokemon deep in the sea.",
    "A somewhat different Ball that works especially well on weaker Pokemon.",
    "A somewhat different Ball that works especially well on Pokemon caught before.",
    "A somewhat different Ball that becomes progressively better the more turns there are in a battle.",
    "A comfortable Ball that makes a captured wild Pokemon quickly grow friendly.",
    "A rare Ball that has been specially made to commemorate an event of some sort.",
    "A spray-type wound medicine. It restores the HP of one Pokemon by 20 points.",
    "A spray-type medicine. It heals one Pokemon from a poisoning.",
    "A spray-type medicine. It heals one Pokemon of a burn.",
    "A spray-type medicine. It defrosts a frozen Pokemon.",
    "A spray-type medicine. It awakens a sleeping Pokemon.",
    "A spray-type medicine. It heals one Pokemon from paralysis.",
    "A medicine that fully restores the HP and heals any status problems of one Pokemon.",
    "A spray-type wound medicine. It fully restores the HP of one Pokemon.",
    "A spray-type wound medicine. It restores the HP of one Pokemon by 200 points.",
    "A spray-type wound medicine. It restores the HP of one Pokemon by 50 points.",
    "A spray-type medicine. It heals all the status problems of one Pokemon.",
    "A medicine that revives a fainted Pokemon, restoring HP by half the maximum amount.",
    "A medicine that revives a fainted Pokemon, restoring HP fully.",
    "Water with a high mineral content. It restores the HP of one Pokemon by 50 points.",
    "A fizzy soda drink. It restores the HP of one Pokemon by 60 points.",
    "A very sweet drink. It restores the HP of one Pokemon by 80 points.",
    "Highly nutritious milk. It restores the HP of one Pokemon by 100 points.",
    "A very bitter medicine powder. It restores the HP of one Pokemon by 50 points.",
    "A very bitter root. It restores the HP of one Pokemon by 200 points.",
    "A very bitter medicine powder. It heals all the status problems of one Pokemon.",
    "A very bitter medicinal herb. It revives a fainted Pokemon, restoring HP fully.",
    "Restores a selected move's PP by 10 points for one Pokemon.",
    "Fully restores a selected move's PP for one Pokemon.",
    "Restores the PP of all moves for one Pokemon by 10 points each.",
    "Fully restores the PP of all moves for one Pokemon.",
    "Lavaridge Town's local specialty. It heals all the status problems of one Pokemon.",
    "A blue glass flute that awakens a sleeping Pokemon.",
    "A yellow glass flute that snaps one Pokemon out of confusion.",
    "A red glass flute that snaps one Pokemon out of infatuation.",
    "A black glass flute. When blown, it makes wild Pokemon levels higher.",
    "A white glass flute. When blown, it makes wild Pokemon levels lower.",
    "A 100% pure juice. It restores the HP of one Pokemon by 20 points.",
    "Revives all fainted Pokemon, restoring HP fully.",
    "Pure salt obtained from deep inside the Shoal Cave. It is extremely salty.",
    "A pretty seashell found deep inside the Shoal Cave. It is striped in blue and white.",
    "A small red shard. It appears to be from some sort of a tool made long ago.",
    "A small blue shard. It appears to be from some sort of a tool made long ago.",
    "A small yellow shard. It appears to be from some sort of a tool made long ago.",
    "A small green shard. It appears to be from some sort of a tool made long ago.",
    "Mahogany Town's famous candy. It heals all the status conditions of a Pokemon.",
    "The Old Chateau's hidden specialty. It heals all the status conditions of a Pokemon.",
    "Castelia City's specialty, soft-serve ice cream. It heals all the status problems of a Pokemon.",
    "A patch that allows a Pokemon to switch to its hidden ability or vice versa.",
    "Shalour City's famous shortbread. It heals all the status conditions of a Pokemon.",
    "An item for use on a Pokemon. It slightly increases the base HP of a single Pokemon.",
    "An item for use on a Pokemon. It slightly increases the base Attack stat of a single Pokemon.",
    "An item for use on a Pokemon. It slightly increases the base Defense stat of a single Pokemon.",
    "An item for use on a Pokemon. It slightly increases the base Sp. Atk stat of a single Pokemon.",
    "An item for use on a Pokemon. It slightly increases the base Sp. Def stat of a single Pokemon.",
    "An item for use on a Pokemon. It slightly increases the base Speed stat of a single Pokemon.",
    "A nutritious drink for Pokemon. It raises the base HP of one Pokemon.",
    "A nutritious drink for Pokemon. It raises the base Attack stat of one Pokemon.",
    "A nutritious drink for Pokemon. It raises the base Defense stat of one Pokemon.",
    "A nutritious drink for Pokemon. It raises the base Speed stat of one Pokemon.",
    "A nutritious drink for Pokemon. It raises the base Sp. Atk stat of one Pokemon.",
    "A candy that is packed with energy. It raises the level of a Pokemon by one.",
    "Slightly raises the maximum PP of a selected move for one Pokemon.",
    "A nutritious drink for Pokemon. It raises the base Sp. Def stat of one Pokemon.",
    "Raises the PP of a selected move to its maximum level for one Pokemon.",
    "A pill that can swap a Pokemon's ability.",
    "An item that prevents stat reduction among party Pokemon for five turns after use.",
    "Raises the critical-hit ratio of Pokemon in battle. Wears off if the Pokemon is withdrawn.",
    "Raises the Attack stat of Pokemon in battle. Wears off if the Pokemon is withdrawn.",
    "Raises the Defense stat of Pokemon in battle. Wears off if the Pokemon is withdrawn.",
    "Raises the Speed stat of Pokemon in battle. Wears off if the Pokemon is withdrawn.",
    "Raises the accuracy stat of Pokemon in battle. Wears off if the Pokemon is withdrawn.",
    "Raises the Sp. Atk stat of Pokemon in battle. Wears off if the Pokemon is withdrawn.",
    "An attractive doll. Use it to flee from any battle with a wild Pokemon.",
    "An attractive item. Use it to flee from any battle with a wild Pokemon.",
    "It is Alola region's local specialty. It can be used once to heal all the status conditions of a Pokemon.",
    "Prevents weak wild Pokemon from appearing for 200 steps.",
    "Prevents weak wild Pokemon from appearing for 250 steps.",
    "A long, durable rope. Use it to escape instantly from a cave or a dungeon.",
    "Prevents weak wild Pokemon from appearing for 100 steps.",
    "An intriguing cable used for linking unknown devices. It helps certain kinds of Pokemon to evolve.",
    "A protective item of some sort. It is extremely stiff and heavy. It is loved by a certain Pokemon.",
    "A box packed with a tremendous amount of electric energy. It is loved by a certain Pokemon.",
    "A box packed with a tremendous amount of magma energy. It is loved by a certain Pokemon.",
    "A transparent device overflowing with dubious data. Its producer is unknown.",
    "A special cloth to be held by a Dusknoir. Moves used by the held Pokemon cannot miss.",
    "A peculiar stone that makes certain species of Pokemon evolve. It is as red as the sun.",
    "A peculiar stone that makes certain species of Pokemon evolve. It is as black as the night sky.",
    "A peculiar stone that makes certain species of Pokemon evolve. It is colored orange.",
    "A peculiar stone that makes certain species of Pokemon evolve. It has a thunderbolt pattern.",
    "A peculiar stone that makes certain species of Pokemon evolve. It is a clear light blue.",
    "A peculiar stone that makes certain species of Pokemon evolve. It has a leaf pattern.",
    "A peculiar stone that makes certain species of Pokemon evolve. It shines with a dazzling light.",
    "A peculiar stone that makes certain species of Pokemon evolve. It is as dark as dark can be.",
    "A peculiar stone that makes certain species of Pokemon evolve. It sparkles like eyes.",
    "A stone that can make certain species of Pokemon evolve. It has a snowflake pattern.",
    "A small and rare mushroom. It is quite popular among certain people.",
    "A large and rare mushroom. It is very popular among certain people.",
    "A rare mushroom that gives off a nice fragrance. It can be sold at a high price to shops.",
    "A relatively small pearl that sparkles in a pretty silver color. It can be sold cheaply.",
    "A quite-large pearl that sparkles in a pretty silver color. It can be sold at a high price.",
    "A pretty red sand with a loose, silky feel. It can be sold at a high price.",
    "A shard of a pretty gem that sparkles in a red color. It can be sold at a high price.",
    "A nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price.",
    "A pretty, heart-shaped scale that is extremely rare. It glows faintly in the colors of a rainbow.",
    "A bone that is extremely valuable for archaeology. It can be sold for a high price to shops.",
    "Very large pearls that sparkle in a pretty silver color. They can be sold at a high price to shops.",
    "A shard that fell to the ground when a comet approached. It can be sold at a high price to shops.",
    "A big nugget of pure gold that gives off a lustrous gleam. It can be sold at a high price to shops.",
    "A sweet honey collected by a Pokemon. It has a lush aroma and can be sold for a low price at shops.",
    "Though this feather is beautiful, it's just a regular feather and has no effect on Pokemon.",
    "A peculiar stone that makes a certain species of Pokemon evolve. It's shaped like an egg.",
    "An item to be held by a Pokemon. It is a sharply hooked claw that ups the holder's critical-hit ratio.",
    "An item to be held by a Pokemon. It may cause the foe to flinch when the holder inflicts damage.",
    "A piece of Mail featuring a cute Zigzagoon print. It is to be held by a Pokemon.",
    "A piece of Mail featuring a cute Wingull print. It is to be held by a Pokemon.",
    "A piece of Mail featuring a cute Pikachu print. It is to be held by a Pokemon.",
    "A piece of Mail featuring a cute Magnemite print. It is to be held by a Pokemon.",
    "A piece of Mail featuring a cute Slakoth print. It is to be held by a Pokemon.",
    "A piece of Mail featuring a cute Wailmer print. It is to be held by a Pokemon.",
    "A piece of Mail to be held by a Pokemon. It will bear the print of the Pokemon holding it.",
    "A piece of Mail featuring a cute Duskull print. It is to be held by a Pokemon.",
    "A piece of Mail featuring a cute Bellossom print. It is to be held by a Pokemon.",
    "A piece of Mail to be held by a Pokemon. It will bear the print of the Pokemon holding it.",
    "A piece of Mail featuring a gorgeous, extravagant print. It is to be held by a Pokemon.",
    "A piece of Mail featuring a print of three cute Pokemon. It is to be held by a Pokemon.",
    "When held by a Pokemon, it will be used in battle to heal paralysis.",
    "When held by a Pokemon, it will be used in battle to wake up.",
    "When held by a Pokemon, it will be used in battle to cure poison.",
    "When held by a Pokemon, it will be used in battle to heal a burn.",
    "When held by a Pokemon, it will be used in battle for defrosting.",
    "When held by a Pokemon, it will be used in battle to restore 10 PP.",
    "When held by a Pokemon, it will be used in battle to restore 10 HP.",
    "When held by a Pokemon, it will be used in battle to lift confusion.",
    "When held by a Pokemon, it will be used in battle to heal any problem.",
    "When held by a Pokemon, it will be used in battle to restore 25% HP.",
    "A hold item that restores HP but may cause confusion when used.",
    "A hold item that restores HP but may cause confusion when used.",
    "A hold item that restores HP but may cause confusion when used.",
    "A hold item that restores HP but may cause confusion when used.",
    "A hold item that restores HP but may cause confusion when used.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Using it on a Pokemon makes it friendlier, but also lowers HP.",
    "Using it on a Pokemon makes it friendlier, but also lowers Attack.",
    "Using it on a Pokemon makes it friendlier, but also lowers Defense.",
    "Using it on a Pokemon makes it friendlier, but also lowers Sp. Atk.",
    "Using it on a Pokemon makes it friendlier, but also lowers Sp. Def.",
    "Using it on a Pokemon makes it friendlier, but also lowers Speed.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "When held by a Pokemon, it raises the Attack stat in a pinch.",
    "When held by a Pokemon, it raises the Defense stat in a pinch.",
    "When held by a Pokemon, it raises the Speed stat in a pinch.",
    "When held by a Pokemon, it raises the Sp. Atk stat in a pinch.",
    "When held by a Pokemon, it raises the Sp. Def stat in a pinch.",
    "When held by a Pokemon, it raises the critical-hit ratio in a pinch.",
    "When held by a Pokemon, it sharply raises one stat in a pinch.",
    "Can be ground up into a powder as an ingredient for medicine.",
    "A mysterious scale that evolves certain Pokemon. It shines in rainbow colors.",
    "A sachet filled with fragrances that are slightly overwhelming. It is loved by a certain Pokemon.",
    "A soft and sweet treat made of whipped and whirled cream. It is loved by a certain Pokemon.",
    "An item to be held by a Pokemon. It casts a tricky glare that lowers the opponent's accuracy.",
    "An item to be held by a Pokemon. It restores any lowered stat in battle. It can be used only once.",
    "An item to be held by a Pokemon. It promotes strong growth but lowers Speed while it is held.",
    "Turning on this special device will allow all Pokemon in your party to receive Exp. from battles.",
    "An item to be held by a Pokemon. A light and sharp claw. The holder may be able to strike first.",
    "An item to be held by a Pokemon. A bell with a comforting chime that makes the holder calm and friendly.",
    "An item to be held by a Pokemon. It snaps the holder out of infatuation. It can be used once.",
    "An item to be held by a Pokemon. This headband ups Attack, but allows the use of only one move.",
    "A peculiar stone that makes certain species of Pokemon evolve. Real king stuff.",
    "An item to be held by a Pokemon. A shiny silver powder that boosts the power of Bug-type moves.",
    "A held item that doubles battle money if the holding Pokemon is in the party.",
    "An item to be held by a Pokemon. It repels wild Pokemon if the holder is first in the party.",
    "An orb to be held by a Latios or Latias. Raises the power of Psychic and Dragon-type moves.",
    "An item to be held by a Pokemon. A fang that gleams a sharp silver. It raises the Sp. Atk stat.",
    "An item to be held by a Pokemon. A scale that shines a faint pink. It raises the Sp. Def stat.",
    "An item to be held by a Pokemon. The holding Pokemon can flee from any wild Pokemon for sure.",
    "An item to be held by a Pokemon. The holding Pokemon is prevented from evolving.",
    "An item to be held by a Pokemon. The holding Pokemon may endure an attack, leaving just 1 HP.",
    "An item to be held by a Pokemon. An egg filled with happiness that earns extra Exp. points in battle.",
    "An item to be held by a Pokemon. A lens that boosts the critical-hit ratio of the holding Pokemon.",
    "An item to be held by a Pokemon. A special metallic film that boosts the power of Steel-type moves.",
    "An item to be held by a Pokemon. The holding Pokemon gradually regains HP during battle.",
    "A thick and tough scale. A Dragon-type Pokemon may be holding it.",
    "An orb to be held by a Pikachu that raises offensive stats. Touching it may cause a shock.",
    "An item to be held by a Pokemon. A loose, silky sand that boosts the power of Ground-type moves.",
    "An item to be held by a Pokemon. An unbreakable stone that boosts the power of Rock-type moves.",
    "An item to be held by a Pokemon. A seed imbued with life that boosts the power of Grass-type moves.",
    "An item to be held by a Pokemon. A shady-looking pair of glasses that boosts Dark-type moves.",
    "An item to be held by a Pokemon. A belt that boosts determination and Fighting-type moves.",
    "An item to be held by a Pokemon. A powerful magnet that boosts the power of Electric-type moves.",
    "An item to be held by a Pokemon. A teardrop-shaped gem that boosts the power of Water-type moves.",
    "An item to be held by a Pokemon. A long, sharp beak that boosts the power of Flying-type moves.",
    "An item to be held by a Pokemon. A small, poisonous barb that boosts the power of Poison-type moves.",
    "An item to be held by a Pokemon. A piece of ice that repels heat and boosts Ice-type moves.",
    "An item to be held by a Pokemon. A sinister, eerie tag that boosts Ghost-type moves.",
    "An item to be held by a Pokemon. A spoon imbued with telekinetic power boosts Psychic-type moves.",
    "An item to be held by a Pokemon. A combustible fuel that boosts the power of Fire-type moves.",
    "An item to be held by a Pokemon. A hard and sharp fang that boosts the power of Dragon-type moves.",
    "An item to be held by a Pokemon. A sumptuous scarf that boosts the power of Normal-type moves.",
    "A transparent device filled with all sorts of data. It is made by Silph Co.",
    "An item to be held by a Pokemon. The holding Pokemon regains some HP upon striking the foe.",
    "An item to be held by a Pokemon. It slightly boosts the power of Water-type moves.",
    "An item to be held by a Pokemon. Its tricky aroma slightly reduces the foe's accuracy.",
    "A glove to be held by a Chansey. It raises Chansey's critical-hit ratio.",
    "A fine, hard powder to be held by a Ditto. It raises Ditto's Defense stat.",
    "A hard bone of some sort to be held by a Cubone or Marowak. It raises the Attack stat.",
    "A held item for Farfetch'd. It raises its critical-hit ratio and speed.",
    "A strawberry-shaped sweet. When a Milcery holds this, it will spin around happily.",
    "A berry-shaped sweet. When a Milcery holds this, it will spin around happily.",
    "A heart-shaped sweet. When a Milcery holds this, it will spin around happily.",
    "A clover-shaped sweet. When a Milcery holds this, it will spin around happily.",
    "A flower-shaped sweet. When a Milcery holds this, it will spin around happily.",
    "A ribbon-shaped sweet. When a Milcery holds this, it will spin around happily.",
    "A star-shaped sweet. When a Milcery holds this, it will spin around happily.",
    "A peculiar apple that can make a certain species of Pokemon evolve. It's exceptionally sweet.",
    "A peculiar apple that can make a certain species of Pokemon evolve. It's exceptionally tart.",
    "A cracked teapot that can make a certain species of Pokemon evolve. Tea poured from it is delicious.",
    "A chipped teapot that can make a certain species of Pokemon evolve. Tea poured from it is delicious.",
    "A cuff made from woven-together Galarica Twigs. Giving it to certain Pokemon will make them happy.",
    "A crown made from woven-together Galarica Twigs. Giving it to certain Pokemon will make them happy.",
    "A quite rare Ball that has been specially crafted to commemorate an ocassion of some sort.",
    "A Ball that makes it easier to catch wild Pokemon at night or in dark places such as caves.",
    "A Ball that restores the caught Pokemon's HP and eliminates any status problem.",
    "A Ball that provides a better catch rate if it is used at the start of a wild encounter.",
    "A Ball that makes it easier to catch Pokemon which are quick to run away.",
    "A Ball that makes it easier to catch Pokemon that are a lower level than your own.",
    "A Ball that is good for catching Pokemon that you reel in with a Rod while out fishing.",
    "A Ball that is better than usual at catching very large and heavy Pokemon.",
    "A Ball for catching Pokemon that are the opposite gender of your Pokemon.",
    "A Ball that will make the wild Pokemon caught with it more friendly toward you.",
    "A Ball that will make it easier to catch Pokemon that can evolve using a Moon Stone.",
    "A special Poke Ball that is used during the Bug-Catching Contest.",
    "A Ball designed to catch Ultra Beasts. It has a low success rate for catching others.",
    "A Ball that activates a Pokemon's hidden ability when caught.",
    "A special Poke Ball for the Pal Park.",
    "An item to be held by a Pokemon. It boosts the holding Pokemon's Cool condition in Contests.",
    "An item to be held by a Pokemon. It boosts the holding Pokemon's Beauty condition in Contests.",
    "An item to be held by a Pokemon. It boosts the holding Pokemon's Cute condition in Contests.",
    "An item to be held by a Pokemon. It boosts the holding Pokemon's Smart condition in Contests.",
    "An item to be held by a Pokemon. It boosts the holding Pokemon's Tough condition in Contests.",
    "A folding bicycle that is at least twice as fast as walking.",
    "A case for holding Coins obtained at the Game Corner. It holds up to 9,999 Coins.",
    "A device used for finding items. If there is a hidden item nearby when it is used, it emits a signal.",
    "An old and beat-up fishing rod. Use it by any body of water to  fish for wild Pokemon.",
    "A new, good-quality fishing rod. Use it by any body of water to  fish for wild Pokemon.",
    "An awesome, high-tech fishing rod. Use it by any body of water to fish for wild Pokemon.",
    "The ticket required for sailing on the ferry S.S. Anne. It has a drawing of a ship on it.",
    "The pass required for entering Pokemon Contests. It has a drawing of an award ribbon on it.",
    "A mysterious ring that enables the use of Z-Power. It requires the willpower of the trainer wearing it.",
    "A nifty watering pail. Use it to promote strong growth in Berries planted in soft soil.",
    "A package that contains mechanical parts of some sort made by the Devon Corporation.",
    "A sack used to collect volcanic ash automatically during walks over deep ash.",
    "The key to New Mauville, which was constructed beneath Mauville City.",
    "A folding bicycle that is capable of stunts like jumps and wheelies.",
    "Unimplemented.",
    "An extremely important letter to Steven from the President of the Devon Corporation.",
    "The ticket required for sailing on a ferry to a distant southern island. It features a drawing of an island.",
    "An orb that glows red. It is said to contain an incredible power from ancient times.",
    "An orb that glows blue. It is said to contain an incredible power from ancient times.",
    "A device used to search for life-forms in water. It looks too difficult to use.",
    "A pair of protective goggles. They enable a Trainer to travel through even desert sandstorms.",
    "A meteorite that fell from space onto Mt. Moon long ago. It is very lumpy and hard.",
    "A key that opens the door to Room 1 inside the Abandoned Ship. It is old and looks easily broken.",
    "A key that opens the door to Room 2 inside the Abandoned Ship. It is old and looks easily broken.",
    "A key that opens the door to Room 4 inside the Abandoned Ship. It is old and looks easily broken.",
    "A key that opens the door to Room 6 inside the Abandoned Ship. It is old and looks easily broken.",
    "A key that opens the storage hold inside the Abandoned Ship. It is old and looks easily broken.",
    "A fossil of an ancient, seafloor- dwelling Pokemon. It appears to be part of a plant root.",
    "A fossil of an ancient, seafloor- dwelling Pokemon. It appears to be part of a claw.",
    "A scope that signals the presence of any unseeable Pokemon. It is made by the Devon Corp.",
    "The foe is fought up close. This cuts the user's Defense and Sp. Def.",
    "Sharp, huge claws hook and slash the foe quickly and with great power.",
    "After attacking, the user switches places with a party Pokemon.",
    "The user shoots a barrage of hard seeds at the foe.",
    "The foe is made to switch out with an ally. In the wild, the battle ends.",
    "A move that badly poisons the foe. Its poison damage worsens every turn.",
    "The user exhales a heated breath to attack. It may also inflict a burn.",
    "The user focuses and rams the foe. It may also make the foe flinch.",
    "The user shoots seeds at the foe. Two to five seeds are shot at once.",
    "An attack that varies in type and intensity depending on the user.",
    "The user electrifies and slams the target. If it misses, the user takes damage instead.",
    "The foe is taunted into a rage that allows it to use only attack moves.",
    "The foe is struck with an icy beam. It may leave the target frostbitten.",
    "The foe is blasted with a blizzard. It may leave the target frostbitten.",
    "The user traps the foe in an electric net. It also lowers the foe's Speed.",
    "A wall of light cuts damage from Sp. Atk attacks for five turns.",
    "Enables the user to evade all attacks. It may fail if used in succession.",
    "A high volume of water is blasted at the foe under great pressure.",
    "A harsh attack that absorbs half the damage it inflicted to restore HP.",
    "The user lets loose a horribly loud shout with the power to damage.",
    "A chilling wind is used to attack. It also lowers the Speed stat.",
    "An attack that varies in power and type depending on the weather.",
    "The foe is slammed with its hard head. It may also make the foe flinch.",
    "A strong electrical attack that may also leave the foe paralyzed.",
    "A brutal lightning attack that may also leave the foe paralyzed.",
    "An earthquake that strikes all Pokemon in battle excluding the user.",
    "This attack move grows more powerful the more the user likes its Trainer.",
    "An attack that hits on the 2nd turn. Can also be used to exit dungeons.",
    "A strong telekinetic attack. It may also lower the foe's Sp. Def stat.",
    "A shadowy blob is hurled at the foe. May also lower the foe's Sp. Def.",
    "An attack that also breaks any barrier like Light Screen and Reflect.",
    "A blast of aura power is let loose at the foe. It is sure to hit.",
    "A wall of light cuts damage from physical attacks for five turns.",
    "Use it to flee from any wild Pokemon. Also warps to the last Poke Center.",
    "The foe is scorched with intense flames. The foe may suffer a burn.",
    "Filthy sludge is hurled at the foe. It may poison the target.",
    "The user fiercely attacks the target using its entire body.",
    "The foe is hit with an intense flame. It may leave the target with a burn.",
    "Boulders are hurled at the foe. It also lowers the foe's Speed if it hits.",
    "A low, tripping kick that inflicts more damage on heavier foes.",
    "The user slams with a forceful water blast. It may lower the foe's Defense.",
    "An attack that is boosted if user is burned, poisoned, or paralyzed.",
    "A strong wind blows away the target's obstacles. It also lowers evasiveness.",
    "The user sleeps for two turns to fully restore HP and heal any status problem.",
    "A sweet kiss that absorbs over half the damage inflicted to restore HP.",
    "An attack that may take the foe's held item if the user isn't holding one.",
    "The foe is hit with wings of steel. It may also raise the user's Defense.",
    "The foe is caught in a fierce wind. It may also confuse the foe.",
    "An attack that absorbs half the damage it inflicted to restore HP.",
    "An intense attack that also sharply reduces the user's Sp. Atk stat.",
    "A basic attack. It can be used to cut down thin trees and grass.",
    "A 2-turn move that hits on the 2nd turn.",
    "A big wave crashes down on the foe. Can also be used for crossing water.",
    "The foe is slugged at maximum power. Can also be used to move boulders.",
    "The user flashes a bright light, which may lower its Attack.",
    "An attack that may also cut Defense. It can also smash cracked boulders.",
    "A powerful charge attack. It can also be used to climb a waterfall.",
    "The user dives underwater on the first turn and strikes next turn.",
    "A Wishing Star has been affixed to it. It lets out a light that allows Pokemon to Dynamax.",
    "A set of false teeth lost by the Safari Zone's Warden. It makes his smile sparkle.",
    "A parcel to be delivered to Prof. Oak from Viridian City's Pokemon Mart.",
    "A flute that is said to instantly awaken any Pokemon. It has a lovely tone.",
    "The key to Cinnabar Island Gym's front door. It is colored red and decorated.",
    "Take this voucher to the Bike Shop in Cerulean City and exchange it for a bicycle.",
    "A ring which enables Pokemon holding a Mega Stone to Mega Evolve in battle.",
    "A piece of amber that contains the genes of an ancient Pokemon. It is clear with a reddish tint.",
    "A card-type key that unlocks doors in Silph Co.'s Head Office in Saffron City.",
    "A key that operates the elevator in Team Rocket's Hideout. It bears the Team Rocket logo.",
    "A fossil of an ancient, seafloor- dwelling Pokemon. It appears to be part of a seashell.",
    "A fossil of an ancient, seafloor- dwelling Pokemon. It appears to be part of a shell.",
    "A scope that makes unseeable Pokemon visible. It is made by Silph Co.",
    "A folding bicycle that allows faster movement than the Running Shoes.",
    "A very convenient map that can be viewed anytime. It even shows your  present location.",
    "This special device can analyze the EVs and IVs of a Pokemon in your party.",
    "A device that enables you to fly to locations you've already visited.",
    "A case that holds TMs and HMs. It is attached to the Bag's compartment for important items.",
    "A pouch for carrying Berries. It is attached to the Bag's compartment for important items.",
    "A television set that is tuned to a program with useful tips for novice Trainers.",
    "A pass for ferries between One, Two, and Three Island. It has a drawing of three islands.",
    "A pass for ferries between Vermilion and the Sevii Islands. It features a drawing of a rainbow.",
    "An aromatic tea prepared by an old lady. It will slake even the worst thirst.",
    "A ticket required to board the ship to Navel Rock. It glows with a mystic light.",
    "A ticket required to board the ship to Birth Island. It glows beautifully.",
    "A device that sends Officer Jenny your current location when used.",
    "An exquisitely beautiful gem that has a red glow. It symbolizes passion.",
    "An exquisitely beautiful gem that has a blue glow. It symbolizes honesty.",
    "?????",
    "A self-healing move that restores HP by up to half of the user's maximum HP.",
    "The user unleashes its power. It may also lower the foe's Sp. Def.",
    "The foe is blasted with natural energy. It may also lower the foe's Sp. Def.",
    "The user glides on the ground to attack. Moves first on Grassy Terrain.",
    "The move's power increases and damages all opposing targets in Psychic Terrain.",
    "The foe is sliced by a blade of air. It may also make the foe flinch.",
    "If the user's previous move failed, power of this move doubles.",
    "The user attacks with voltage that doubles its power on Electric Terrain.",
    "The foe is attacked with a shock wave generated by the user's gaping mouth.",
    "A harsh punch that absorbs half the damage it inflicted to restore HP.",
    "A sinister, bluish white flame is shot at the foe to inflict a burn.",
    "An attack with a steel-hard tail. It may lower the foe's Defense stat.",
    "The foe is soaked by a special acid. Its power doubles if the foe is poisoned.",
    "The user explodes to inflict terrible damage even while fainting itself.",
    "Claws made of shadows rake the foe. It has a high critical-hit ratio.",
    "It fires a beam of steel from its body, which also hurts the user.",
    "The user controls the target's item to attack. Fails if the target has no item.",
    "The user hits the foe with two brutal strikes in one turn.",
    "If the user's previous move failed, power of this move doubles.",
    "A 3-kick attack that becomes more powerful with each successive hit.",
    "The foe is stabbed by sharpened stones. It has a high critical-hit ratio.",
    "The user attacks with a blast that beats fairy immunities but hurts the user.",
    "A weak electric shock that is sure to cause paralysis if it hits.",
    "A high-speed spin. The slower the user is than the foe, the greater the damage.",
    "If foe has a held item, it's knocked off and is dealt extra damage.",
    "The ground under the foe erupts. It may also lower the foe's Sp. Def.",
    "The foe is punched with an electrified fist. It may leave the foe paralyzed.",
    "The user attacks the foe's legs, lowering its Speed stat.",
    "The user releases a horrible aura that may also make the foe flinch.",
    "Large boulders are hurled at the foe. It may make the foe flinch.",
    "The user slashes the foe with crossed claws as if they were scissors.",
    "While asleep, the user randomly uses one of the moves it knows.",
    "Boiling water is shot at the foe. It may also cause a burn.",
    "The foe is stabbed by an arm steeped in poison. It may also poison the foe.",
    "Two turns after this move is used, the foe is attacked psychically.",
    "Grass snares and trips the foe. It does more damage to heavier foes.",
    "An extremely fast attack against one target. It can't be evaded.",
    "The user pecks the foe, plucking its berry if it is holding one.",
    "After attacking, the user switches places with a party Pokemon.",
    "Filthy garbage is shot at the foe. It may also poison the target.",
    "Light energy is shot at the foe. It may also lower the foe's Sp. Def.",
    "After attacking, the user switches places with a party Pokemon.",
    "The foe is made to switch out with an ally. In the wild, the battle ends.",
    "It hits two to five times in a row. Raises Speed, but lowers Defense.",
    "The user absorbs a mystic power to raise its Defense and Sp. Def.",
    "The user hits all Pokemon in battle by stomping. Lowers Speed of those hit.",
    "The user blows cold air that always lands a critical hit. It can also freeze.",
    "The foe is punched with a fiery fist. It may leave the foe with a burn.",
    "The user throws an electrified tackle. It hurts the user a little.",
    "The user slams the target with its wings. The target is hit twice in a row.",
    "The foe is punched with an icy fist. It may leave the foe frostbitten.",
    "The user damages opposing Pokemon by emitting a powerful flash.",
    "The area around the user is swamped by a giant sludge wave. May poison.",
    "An odd psychic wave attacks the target. This attack does physical damage.",
    "The user damages and also blocks the target from heal moves for 3 turns.",
    "A nimble attack that does double damage if the user has no held item.",
    "The move's type and power depends on the terrain currently used in battle.",
    "The user barks menacingly. It also lowers the foe's Sp. Atk.",
    "A powerful attack, but it also lowers the user's Attack and Defense stats.",
    "The user throws scorching sand at the target. It may also inflict burn.",
    "The user sends a wave of vacuum at the foe. It will strike first.",
    "The user explodes. It halves SpecDef, and becomes stronger in Misty Terrain.",
    "The foe is roughed up by the user. This may lower the foe's Attack.",
    "The more the user outweighs the foe, the greater the damage.",
    "The higher the user's Defense, the more damage it will inflict.",
    "The user creates a bizarre area in which slower Pokemon get to move first.",
    "The user tucks in its wings and charges. It also hurts the user.",
    "The user attacks and removes terrain. The move fails if there's no terrain.",
    "An intense attack that also sharply reduces the user's Sp. Atk stat.",
    "The user spins with ice, dealing damage and destroying terrain.",
    "If held, reduces damage taken from one super effective Fire-move.",
    "If held, reduces damage taken from one super effective Water-move.",
    "If held, reduces damage taken from one super effective Electric-move.",
    "If held, reduces damage taken from one super effective Grass-move.",
    "If held, reduces damage taken from one super effective Ice-move.",
    "If held, reduces damage taken from one super effective Fighting-move.",
    "If held, reduces damage taken from one super effective Poison-move.",
    "If held, reduces damage taken from one super effective Ground-move.",
    "If held, reduces damage taken from one super effective Flying-move.",
    "If held, reduces damage taken from one super effective Psychic-move.",
    "If held, reduces damage taken from one super effective Bug-move.",
    "If held, reduces damage taken from one super effective Rock-move.",
    "If held, reduces damage taken from one super effective Ghost-move.",
    "If held, reduces damage taken from one super effective Dragon-move.",
    "If held, reduces damage taken from one super effective Dark-move.",
    "If held, reduces damage taken from one super effective Steel-move.",
    "If held, reduces damage taken from one Normal-move.",
    "If held by a Pokemon, it increases Accuracy just once in a pinch.",
    "If held by a Pokemon, it gets to move first just once in a pinch.",
    "When the holder is hit with a physical move, the attacker is hurt.",
    "When the holder is hit with a special move, the attacker is hurt.",
    "If held, reduces damage taken from one super effective Fairy-move.",
    "When the holder is hit by a physical attack, its Defense will increase.",
    "When the holder is hit by a special attack, its Sp. Def will increase.",
    "An oval charm said to increase the chance of Eggs being found at the Day Care.",
    "A shiny charm said to increase the chance of finding a Shiny Pokemon.",
    "A mystical rainbow feather that sparkles.",
    "A strange, silvery feather that sparkles.",
    "A stone formed by boulders that melted in hot magma, and hardened. Magma still remains inside it.",
    "Reshiram's body was destroyed and changed into this stone. It is said to be waiting for a hero.",
    "Zekrom's body was destroyed and changed into this stone. It is said to be waiting for a hero.",
    "It is said that the tones it produces were offered up as an expression of gratitude.",
    "It is said that the tones it produces were offered up as an expression of gratitude.",
    "A flower bundled in bouquets to convey gratitude on nice occasions. It allows Shaymin to change forme.",
    "A splicer that fuses or separates Kyurem and Reshiram or Zekrom.",
    "A glass that reveals the truth. It's a mysterious glass that returns a Pokemon to its original shape.",
    "A bottle believed to have been used to seal away the power of a certain Pokemon long, long ago.",
    "A machine to fuse or separate Necrozma, which needs light, and Solgaleo.",
    "A machine to fuse or separate Necrozma and Lunala or Solgaleo.",
    "It is said that a hero used this sword to halt a disaster in ancient times, but it has since worn out.",
    "It is said that a hero used this shield to halt a disaster in ancient times, but it has since worn out.",
    "A gleaming orb to be held by Dialga. It boosts the power of Dragon- and Steel-type moves when held.",
    "A glowing orb to be held by Palkia. It boosts the power of Dragon- and Water-type moves when held.",
    "A glowing orb to be held by Giratina. It boosts the power of Dragon- and Ghost-type moves when held.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Fighting-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Flying-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Poison-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Ground-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Rock-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Bug-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Ghost-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Steel-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Fire-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Water-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Grass-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Electric-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Psychic-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Ice-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Dragon-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Dark-type moves.",
    "An item to be held by a Pokemon. It is a stone tablet that boosts the power of Fairy-type moves.",
    "A memory disc that contains Fighting-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Flying-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Poison-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Ground-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Rock-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Bug-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Ghost-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Steel-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Fire-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Water-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Grass-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Electric-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Psychic-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Ice-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Dragon-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Dark-type data. It changes the type of Silvally if held.",
    "A memory disc that contains Fairy-type data. It changes the type of Silvally if held.",
    "A cassette to be held by Genesect. It changes Techno Blast to a Fire-type move.",
    "A cassette to be held by Genesect. It changes Techno Blast to a Water-type move.",
    "A cassette to be held by Genesect. It changes Techno Blast to a Electric-type move.",
    "A cassette to be held by Genesect. It changes Techno Blast to a Ice-type move.",
    "A flower nectar obtained at Ula'ula Meadow. It changes the form of certain species of Pokemon.",
    "A flower nectar obtained at Melemele Meadow. It changes the form of certain species of Pokemon.",
    "A flower nectar obtained at Royal Avenue. It changes the form of certain species of Pokemon.",
    "A flower nectar obtained at Poni Meadow. It changes the form of certain species of Pokemon.",
    "Have Necrozma hold this, and this stone will enable it to Ultra Burst during battle.",
    "Have Venusaur hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Charizard hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Charizard hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Blastoise hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Beedrill hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Pidgeot hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Alakazam hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Slowbro hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Gengar hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Kangaskhan hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Pinsir hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Gyarados hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Aerodactyl hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Mewtwo hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Mewtwo hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Ampharos hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Steelix hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Scizor hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Heracross hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Houndoom hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Tyranitar hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Sceptile hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Blaziken hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Swampert hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Gardevoir hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Sableye hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Mawile hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Aggron hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Medicham hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Manectric hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Sharpedo hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Camerupt hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Altaria hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Banette hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Absol hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Glalie hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Salamence hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Metagross hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Latias hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Latios hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Lopunny hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Garchomp hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Lucario hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Abomasnow hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Gallade hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Audino hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Diancie hold this, and this stone will enable it to Mega Evolve during battle.",
    "This is a crystallized form of Z-Power. It upgrades Normal-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Fighting-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Flying-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Poison-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Ground-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Rock-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Bug-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Ghost-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Steel-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Fire-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Water-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Grass-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Electric-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Psychic-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Ice-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Dragon-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Dark-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Fairy-type moves to Z-Moves.",
    "This is a crystallized form of Z-Power. It upgrades Alolan Raichu's Thunderbolt to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Decidueye's Spirit Lock to a Z-Move.",
    "A special form of Z-Power that upgrades an Eeveelution's Last Resort to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Incineroar's Dark Lariat to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Kommo-o's Clang Scales to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Lunala's Geist Beam to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Lycanroc's Stone Edge to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Marshadow's Spect Thief to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Mew's Psychic to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Mimikyu's Play Rough to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Pikachu's Volt Tackle to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades a Thunderbolt by Pikachu in a cap to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Primarina's Sparkle Aria to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Snorlax's Giga Impact to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades Solgaleo's Sunsteel Strike to a Z-Move.",
    "This is a crystallized form of Z-Power. It upgrades the tapu's Nature's Mad to a Z-Move.",
    "A item to be held by a Pokemon. It strengthens Pokemon that have certain abilities.",
    "A item to be held by a Pokemon. It ensures the holder's multistrike moves hit more times.",
    "A green Apricorn. It has a mysterious, aromatic scent.",
    "A pink Apricorn. It has a nice, sweet scent.",
    "A red Apricorn. It assails your nostrils.",
    "A held item that boosts speed when held by Porygon-Z, but prevents same move used twice in a row.",
    "An item that evokes memories of its past selves. Boosts Fighting moves when held by Electivire.",
    "A carved mask that when held by Ogerpon allows it to wield the Rock type and boosts its power by 20%.",
    "A carved mask that when held by Ogerpon allows it to wield the Fire type and boosts its power by 20%.",
    "A carved mask that when held by Ogerpon allows it to wield the Water type and boosts its power by 20%.",
    "A carved mask that when held by Ogerpon allows it to return to its default form.",
    "An item that evokes memories of its past selves. Boosts Fire moves when held by Sunflora.",
    "When held by Magmortar, it lowers target's Speed and afflicts it with tar after hitting a Fire move.",
    "A heavy crown made by an ancient civilization about 3000 years ago.",
    "A fossil from a prehistoric Pokemon that lived on the land. It appears to be part of a head.",
    "A fossil from a prehistoric Pokemon that lived on the land. It appears to be part of a collar.",
    "A fossil of an ancient Pokemon that lived in the sea. It appears to be part of its back.",
    "A fossil of an ancient Pokemon that flew in the sky. It appears to be part of its wing.",
    "A fossil from an ancient Pokemon that once lived on the land. It looks like a piece of large jaw.",
    "A fossil from an ancient Pokemon that once lived on land. It looks like the impression from a skin sail.",
    "A fossil of an ancient Pokemon that soared through the sky. What it looked like is a mystery.",
    "A fossil of an ancient Pokemon that once lived in the sea. What it looked like is a mystery.",
    "A fossil of an ancient Pokemon that once roamed the land. What it looked like is a mystery.",
    "A fossil of an ancient Pokemon that once lived in the sea. What it looked like is a mystery.",
    "An item needed to keep a stone tower from collapsing. Voices can be heard from it occasionally.",
    "A bottle cap that gives off a silver gleam. Some people are happy to receive one.",
    "A bottle cap that gives off a golden gleam. Some people are happy to receive one.",
    "Throw one into a Pokemon Den to attract a wild Dynamax Pokemon.",
    "A Pokemon held item that promotes Attack gain on leveling, but reduces the Speed stat.",
    "A Pokemon held item that promotes Defense gain on leveling, but reduces the Speed stat.",
    "A Pokemon held item that promotes Special Attack gain on leveling, but reduces the Speed stat.",
    "A Pokemon held item that promotes Special Defense gain on leveling, but reduces the Speed stat.",
    "A Pokemon held item that promotes Speed gain on leveling, but reduces the Speed stat.",
    "A Pokemon held item that promotes HP gain on leveling, but reduces the Speed stat.",
    "An item to be held by a Pokemon. It doubles the battle money if the holding Pokemon takes part.",
    "An item to be held by a Pokemon. An exotic incense that makes the holder bloated and slow moving.",
    "An item to be held by a Pokemon. This exotic incense boosts the power of Psychic-type moves.",
    "An item to be held by a Pokemon. It repels wild Pokemon if the holder is first in the party.",
    "An item to be held by a Pokemon. It is an exotic incense that boosts the power of Rock-type moves.",
    "An item to be held by a Pokemon. It is an exotic incense that boosts the power of Grass-type moves.",
    "An item to be held by a Pokemon. It is an exotic incense that boosts the power of Water-type moves.",
    "A gem with an ordinary essence. When held, it strengthens the power of a Normal-type move once.",
    "A gem with an essence of combat. When held, it strengthens the power of a Fighting-type move once.",
    "A gem with an essence of air. When held, it strengthens the power of a Flying-type move once.",
    "A gem with an essence of poison. When held, it strengthens the power of a Poison-type move once.",
    "A gem with an essence of land. When held, it strengthens the power of a Ground-type move once.",
    "A gem with an essence of rock. When held, it strengthens the power of a Rock-type move once.",
    "A gem with an insect-like essence. When held, it strengthens the power of a Bug-type move once.",
    "A gem with a spectral essence. When held, it strengthens the power of a Ghost-type move once.",
    "A gem with an essence of steel. When held, it strengthens the power of a Steel-type move once.",
    "A gem with an essence of fire. When held, it strengthens the power of a Fire-type move once.",
    "A gem with an essence of water. When held, it strengthens the power of a Water-type move once.",
    "A gem with an essence of nature. When held, it strengthens the power of a Grass-type move once.",
    "A gem with an essence of electricity. When held, it strengthens the power of an Electric-type move once.",
    "A gem with an essence of the mind. When held, it strengthens the power of a Psychic-type move once.",
    "A gem with an essence of ice. When held, it strengthens the power of an Ice-type move once.",
    "A gem with a draconic essence. When held, it strengthens the power of a Dragon-type move once.",
    "A gem with an essence of darkness. When held, it strengthens the power of a Dark-type move once.",
    "A gem with an essence of the fey. When held, it strengthens the power of a Fairy-type move once.",
    "An item to be held by a Pokemon. It is a magnifying lens that boosts the accuracy of moves.",
    "An item to be held by a Pokemon. It is a headband that slightly boosts the power of physical moves.",
    "An item to be held by a Pokemon. This thick pair of glasses slightly boosts the power of special moves.",
    "An item to be held by a Pokemon. It's a well-worn belt that boosts the power of super effective moves.",
    "A hold item that extends the duration of moves like Reflect and Light Screen used by the holder.",
    "An item to be held by a Pokemon. It boosts the power of moves, at the cost of some HP on each hit.",
    "A single-use item to be held by a Pokemon. It allows a charging move on the first turn immediate usage.",
    "An item to be held by a Pokemon. It is a bizzare orb that badly poisons the holder in battle.",
    "An item to be held by a Pokemon. It is a bizarre orb that inflicts a burn on the holder in battle.",
    "An item to be held by Ditto. Extremely fine yet hard, this odd powder boosts the Speed stat.",
    "An item to be held by a Pokemon. If holder has full HP, it will endure a KO attack with 1 HP.",
    "An item to be held by a Pokemon. If the holder moves after the foe, its accuracy will be boosted.",
    "An item to be held by a Pokemon. It boosts moves used consecutively until a different move is used.",
    "A Pokemon held item that cuts Speed. It allows Ground-type moves to hit Flying and levitating Pokemon.",
    "An item to be held by a Pokemon. It is tremendously heavy and makes the holder move slower than usual.",
    "An item to be held by a Pokemon. If the holder becomes infatuated, the opposing Pokemon will be, too.",
    "An item to be held by a Pokemon. Poison-type Pokemon regain HP, but it damages any other type.",
    "An item to be held by a Pokemon. It extends the duration of the move Hail when used by the holder.",
    "An item to be held by a Pokemon. It extends the duration of the move Sandstorm when used by the holder.",
    "An item to be held by a Pokemon. It extends the duration of the move Sunny Day when used by the holder.",
    "An item to be held by a Pokemon. It extends the duration of the move Rain Dance when used by the holder.",
    "An item to be held by a Pokemon. It extends the duration of multi- turn attacks like Bind or Wrap.",
    "An item to be held by a Pokemon. This scarf boosts Speed, but allows the use of only one move.",
    "An item to be held by a Pokemon. These glasses raise Sp. Atk, but allows the use of only one move.",
    "A held item that damages the holder every turn and latches on to Pokemon that touch the holder.",
    "An item to be held by a Pokemon. This carapace enables the holder to switch out of battle without fail.",
    "An item to be held by a Pokemon. It boosts the amount of HP the holder recovers from HP-stealing moves.",
    "An item that raises the defenses of Pokemon that are capable of evolution.",
    "An item to be held by a Pokemon. This very light stone reduces the weight of a Pokemon when held.",
    "An item to be held by a Pokemon. If the holder is hit, the attacker will also be damaged upon contact.",
    "An item to be held by a Pokemon. The holder floats in the air until hit. Once hit, this item will burst.",
    "An item to be held by a Pokemon. If the holder is hit by an attack, the attacker is removed from battle.",
    "An item to be held by a Pokemon. Moves that normally have no effect will land on a Pokemon holding it.",
    "An item to be held by a Pokemon. A band that increases the power of binding moves used by the holder.",
    "An item to be held by a Pokemon. It boosts Sp. Atk if hit with a Water-type attack once.",
    "An item to be held by a Pokemon. It boosts Attack if hit with an Electric-type attack once.",
    "An item to be held by a Pokemon. If the holder is hit by an attack, it will be switched out of battle.",
    "An item to be held by a Pokemon.  Atk and Sp. Atk. increase if it is hit with a move it's weak to.",
    "An item to be held by a Pokemon. This vest raises Sp. Def but prevents the use of status moves.",
    "An item to be held by a Pokemon. It boosts Sp. Def if hit with a Water-type attack once.",
    "An item to be held by a Pokemon. It boosts Attack if hit with an Ice-type attack once.",
    "These goggles protect the holder  from both weather-related damage and powder.",
    "An item to be held by a Pokemon. It boosts Speed if the holder is intimidated.",
    "An item to be held by a Pokemon. It extends the terrain duration of the holder's move or ability.",
    "An item that protects the holder from effects caused by making direct contact with the enemy.",
    "An item to be held by a Pokemon. It boosts Defense on Electric Terrain. It can only be used once.",
    "An item to be held by a Pokemon. It boosts Defense on Grassy Terrain. It can only be used once.",
    "An item to be held by a Pokemon. It boosts Sp. Defense on Misty Terrain. It can only be used once.",
    "An item to be held by a Pokemon. It boosts Sp. Defense on Psychic Terrain. It can only be used once.",
    "An item to be held by a Pokemon. When stats are lowered, the holder will be switched out of battle.",
    "An item to be held by a Pokemon. It lower's the holder's Speed when Trick Room takes effect.",
    "An item to be held by a Pokemon. It raises Speed when a Pokemon misses a move due to accuracy.",
    "An item to be held by a Pokemon. These boots prevent the effects of traps set on the battlefield.",
    "An item to be held by a Pokemon. This sturdy umbrella protects the holder from the effects of weather.",
    "An item to be held by a Pokemon. It raises Sp. Atk when a Pokemon uses a sound-based move.",
    "Have Machamp hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Lapras hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Butterfree hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Garbodor hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Snorlax hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Kingler hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Toxtricity hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Coalossal hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Duraludon hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Drednaw hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Copperajah hold it, and this stone will enable it to Mega Evolve during battle.",
    "Have Flapple or Appletun hold it to enable them to Mega Evolve during battle.",
    "Have Orbeetle hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Grimmsnarl hold it, and this stone will enable it to Mega Evolve during battle.",
    "A specially crafted medicine made by Nurse Joy.",
    "Have Centiskorch hold it, and this stone will enable it to Mega Evolve during battle.",
    "Have Sandaconda hold this, and this stone will enable it to Mega Evolve during battle.",
    "Have Alcremy hold this, and this stone will enable it to Mega Evolve during battle.",
    "?????",
    "A held item that boosts the power of punching moves and prevents direct contact with targets.",
    "?????",
    "?????"
  ]
};
});
