moveChanges = {"Renegade Platinum": 
{
    "Barrage":     "Draining Kiss",
    "Brine":        "Scald",
    "Constrict":    "Icicle Crash",
    "Horn Drill":   "Drill Run",
    "Lunar Dance":  "Moonblast",
    "Luster Purge": "Dazzling Gleam",
    "Mist Ball":    "Disarming Voice",
    "Sand Tomb":    "Bulldoze",
    "Submission":   "Play Rough",
    "Twister":      "Hurricane",
    "Volt Tackle":  "Wild Charge",
    "HP Bug": "Hidden Power Bug",
    "HP Dark": "Hidden Power Dark",
    "HP Dragon": "Hidden Power Dragon",
    "HP Electric": "Hidden Power Electric",
    "HP Fighting": "Hidden Power Fighting",
    "HP Fire": "Hidden Power Fire",
    "HP Flying": "Hidden Power Flying",
    "HP Ghost": "Hidden Power Ghost",
    "HP Grass": "Hidden Power Grass",
    "HP Ground": "Hidden Power Ground",
    "HP Ice": "Hidden Power Ice",
    "HP Normal": "Hidden Power Normal",
    "HP Poison": "Hidden Power Poison",
    "HP Psychic": "Hidden Power Psychic",
    "HP Rock": "Hidden Power Rock",
    "HP Steel": "Hidden Power Steel",
    "HP Water": "Hidden Power Water",
}}